plankanban/planka

client/src/components/Projects/Projects.module.scss
Hey,
on phones or smaller displays in general, if the title of a project is too long for the box, it overflows.
I've added hyphenation/word-break to the scss file (hyphens if browser/word supports it, and word-break if not).
=> Fix project title word break on projects overview page

client/public/index.html, client/src/components/Login/Login.jsx, client/src/locales/cs/embed.js, client/src/locales/de/embed.js, client/src/locales/en/embed.js, client/src/locales/es/embed.js, client/src/locales/fr/embed.js, client/src/locales/pl/embed.js, client/src/locales/ru/embed.js
In a few source files this word was misspelled. I noticed it right away on the login screen of my self-hosted instance.
=> Fix misspelling of "management".

Dockerfile, docker-start.sh
The current Dockerfile performs an expensive install of all node modules for every source change. That's not necessary as npm install only depends on the `package.json`, `package-lock.json` and `.npmrc` files. This change leads to much better use of Docker's layer cache, keeping all NPM packages in a cached layer as long as only code is changed.
It also fixes an issue where SIGTERMs sent to the container wouldn't get delivered to NodeJS because bash ran as PID 1 and does not forward signals. By exec'ing into node it is now PID 1 inside the container and thus gets the SIGTERM directly.
=> Improve Docker cache efficiency and fix signal handling

server/db/init.js
Migrations should never be updated or deleted, all changes to the schema should happen through `knex migrate:make` so whenever a user runs newer version - their DB schema gets updated automatically.
=> Migrations: alway apply migrations on start-up

server/db/migrations/20180721234154_create_project_manager_table.js
Reflect the name change of the table to 'project_manager' also in the down command.
=> DB Migration: ProjectManager wrong "down"-name

client/package-lock.json, client/package.json, client/src/lib/custom-ui/components/Markdown/Markdown.jsx
related: #257
By introducing [remarkjs/remark-breaks](https://github.com/remarkjs/remark-breaks) as a Markdown plugin, users can realize general line breaks in the comment and description fields.
=> Add remark breaks plugin for line breaks.

client/src/components/LabelsStep/AddStep.jsx, client/src/components/LabelsStep/LabelsStep.jsx
This PR updates the label creation workflow.
When you search for a label name and no matching label exists with that name, you have the option of creating a new label. However, currently you have to enter the label name again. After this change, the label name field is pre-filled with the last value of the search field.
[Screen recording](https://user-images.githubusercontent.com/9086585/193411488-b013d20a-99b3-41da-963c-bca8dfd9ce2f.webm)
=> feat: Prefill label creation with search term

package.json
FIxed npm install errors on Windows
Working on: Windows 10 (10.0.19044), Ubuntu 22.04.1
There seems to be an issue with --prefix on Windows, but only in npm install.
() to start a subshell and don't change dir, but it should also work without it.
=> fix: Fix npm install errors on Windows

docker-compose.yml, server/.env.sample, server/db/knexfile.js
At the moment knex.js does not pass down connection query parameters to build the connection.
Related: https://github.com/knex/knex/issues/2354
This can be bypassed by setting the corresponding environment variable `PGSSLMODE`.
This PR provides the corresponding documentation. I couldn't find the source code for the official website, so I put this into two places:
- server/.env.sample
- docker-compose.yml
So far there is a ticket open to allow connections to Postgres databases, that offer a self-signed certificate: https://github.com/plankanban/planka/issues/261
This PR will make a change on how the connection string is build, that should be backwards compatible and allows the usage of self-signed certificates.
=> allow postgres connections, that require ssl mode

client/src/components/CardModal/Activities/CommentEdit.jsx
Fixes: #441 
This PR is a proposed fix for the linked issue by not reverting the text-state onBlur callbacks.  This achieves parity with the card Add/Edit description functionality where the "Save" button remains visible with the same focus/blur actions.
=> Fix: Keep comment edits when textarea loses focus

client/src/components/Header/Header.jsx, client/src/components/Header/Header.module.scss
Closes #450 
Adds the "edit" icon to the project header tab to be a more intuitive target for opening the project-edit-modal.
=> Feat: add edit icon to project tab component

charts/planka/Chart.yaml, charts/planka/templates/deployment.yaml, charts/planka/values.yaml
Fixes #496 
Sets an overall baseUrl value to remove the need for an ingress to set a custom host.
Tested with baseUrl set and unset and behaving as desired. I don't have then environment to triple-check if the ingress method still works but it should.
=> fix(#496): Helmchart - Decoupled BASE_URL from Ingress Host

docker-compose-dev.yml, docker-compose.yml, server/.env.sample, server/api/helpers/users/get-or-create-one-using-oidc.js, server/config/custom.js
Implements #533 and provides a solution to administrate users and roles in planka instead over the token claims from the oidc provider.
=> feat: Add OIDC_IGNORE_ROLES to disable updating isAdmin on SSO login

client/src/locales/ja/core.js
Fixes issue #542
|before|after|
|---|---|
|<img width="220" alt="image" src="https://github.com/plankanban/planka/assets/34591767/559e2c94-79e6-4220-abd6-c9778bec35ec">|<img width="215" alt="image" src="https://github.com/plankanban/planka/assets/34591767/11b916f6-b629-43a4-9868-0b1acb630c71">|
=> fix #542: Fix time format in japanese locale

charts/planka/templates/deployment.yaml, charts/planka/values.yaml
Planka cannot be accessed if `service.port` is set to anything other than `1337`.
The cause is that the value of `service.port` is set for containerPort.
<details>
<summary>CrashLoopBackOff Error in Kubernetes:</summary>
The following example is when `service.port` is set to `80`:
```
% kubectl get svc
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
planka                 LoadBalancer   10.97.160.112    localhost     80:30767/TCP   93s
planka-postgresql      ClusterIP      10.111.218.220   <none>        5432/TCP       93s
planka-postgresql-hl   ClusterIP      None             <none>        5432/TCP       93s
% kubectl get po
NAME                      READY   STATUS    RESTARTS      AGE
planka-54bb896cb8-ppt4n   0/1     Running   1 (11s ago)   108s …
```
=> Fix containerPort to not be affected by service.port in helm

charts/planka/Chart.yaml, charts/planka/templates/deployment.yaml, charts/planka/templates/secret-oidc.yaml, charts/planka/values.yaml
In this PR, makes it easier to configure an oidc thru helm.
For example:
```yaml
oidc:
enabled: true
clientId: sxxaAIAxVXlCxTmc1YLHBbQr8NL8MqLI2DUbt42d
clientSecret: om4RTMRVHRszU7bqxB7RZNkHIzA8e4sGYWxeCwIMYQXPwEBWe4SY5a0wwCe9ltB3zrq5f0dnFnp34cEHD7QSMHsKvV9AiV5Z7eqDraMnv0I8IFivmuV5wovAECAYreSI
issuerUrl: https://auth.local/application/o/planka/
admin:
roles:
- planka-admin
```
```
% kubectl describe deploy planka
Name:                   planka
Namespace:              planka
CreationTimestamp:      Sat, 18 Nov 2023 11:10:12 +0900
Labels:                 app.kubernetes.io/instance=planka
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=planka
app.kubernetes.io/version=1.15.0
helm.sh/chart=planka-0.1.10
Annotations:            deployment.kubernetes.io/revision: 1 …
```
=> fix #548: Add support for OIDC configuration thru the helm

client/package.json
`npm run build` failed inside the client folder under Windows. A lot of errors reported, in the form of:
> [eslint]
> src\actions\activities.js
>   Line 1:52:   Delete \`␍\` prettier/prettier
And it went on and on, for different files.
Fixed as suggested in this SO reply:
https://stackoverflow.com/a/53769213
=> Fixed broken build under Windows.

client/src/components/CardModal/Activities/Item.jsx, client/src/components/CardModal/Activities/ItemComment.jsx, client/src/components/DueDate/DueDate.jsx, client/src/locales/cs/core.js, client/src/locales/da/core.js, client/src/locales/de/core.js, client/src/locales/en/core.js, client/src/locales/es/core.js, client/src/locales/fr/core.js, client/src/locales/it/core.js, client/src/locales/ja/core.js, client/src/locales/ko/core.js, client/src/locales/pl/core.js, client/src/locales/ro/core.js, client/src/locales/ru/core.js, client/src/locales/sk/core.js, client/src/locales/sv/core.js, client/src/locales/tr/core.js, client/src/locales/uz/core.js, client/src/locales/zh/core.js, client/src/utils/get-date-format.js
Added fullDate and fullDateTime parameters.
Please let me know if the datetime format is incorrect.
Related to #73 
> When a date is outside the current year, show the year
so, if the due date is on the January 13 2021, leave it like it is now, Jan 13, but if it's, for example, January 13 2022, also show the date: Jan 13 2022)
=> feat: Add ability to display year only when it is not the current year

docker-compose-dev.yml, docker-compose.yml, server/.env.sample, server/api/controllers/cards/create.js, server/api/controllers/comment-actions/create.js, server/api/helpers/actions/create-one.js, server/api/helpers/cards/create-one.js, server/api/helpers/cards/update-one.js, server/api/helpers/notifications/create-one.js, server/api/helpers/utils/send-email.js, server/api/hooks/smtp/index.js, server/config/custom.js, server/package-lock.json, server/package.json
Sends emails to notification receivers on Comment Card actions.
**New env vars**
```
SMTP_HOST=
SMTP_USER=
SMTP_PASSWORD=
SMTP_PORT=587
SMTP_SECURE=
SMTP_FROM="Demo Demo" <demo@demo.demo>
```
More action types could be supported in a similar way.
**This adds [nodemailer](https://nodemailer.com) as a dependency**
=> feat: send emails on Comment Card notifications

charts/planka/Chart.yaml, charts/planka/templates/deployment.yaml, charts/planka/values.yaml
Some helm users might want to turn off the built-in postgres installation, but the deployment template statically refers to a secret created by the postgresql chart.
If postgres.enabled is set to false, we should ask for a dburl parameter for an external postgres and use that in the environment instead.
The behavior if postgres.enabled == true remains unchanged.
=> fix: Allow specifying an external dburl in helm

charts/planka/Chart.yaml, charts/planka/templates/deployment.yaml
This PR succeds https://github.com/plankanban/planka/pull/681
When `securityContext.readOnlyRootFilesystem: true`  is true, an emptyDir volumeMount is added. 
This is an ephemeral storage location for the contents of `/app/logs`
=> feat: Ensure container can run with readOnlyRootFilesystem

.github/workflows/build-and-push-docker-base-image.yml, .github/workflows/build-and-push-docker-image-dev.yml, .github/workflows/build-and-push-docker-image.yml
I use renovate to make sure my deployed apps are up to date. ([see](https://github.com/halkeye/home-k8s/pull/94)) and according to the [documentation](https://docs.renovatebot.com/modules/datasource/docker/) if the source docker label is set, it'll actually pull in the release notes.
I checked the latest release, and it doesn't seem to have the labels (or any labels) set, so using the pre-existing github action should populate all the nice metadata.
```
regctl image config --format '{{ jsonPretty .Config.Labels }}' ghcr.io/plankanban/planka
null
```
=> Use docker/metadata-action to make sure all opencontainer labels are set

charts/planka/Chart.yaml, charts/planka/templates/deployment.yaml
A fix to https://github.com/plankanban/planka/issues/750 
The helm playground accepted the variable without the `{{ }}` but it appears that was not valid. This should hopefully render the template properly
=> Fix Helm template for DBURI Secret

client/src/components/Card/NameEdit.jsx, client/src/components/CardModal/Activities/CommentEdit.jsx, client/src/components/CardModal/Tasks/NameEdit.jsx, client/src/components/List/NameEdit.jsx, client/src/utils/element-helpers.js
When editing certain fields on the client, the cursor currently defaults to the beginning of the text. Based on my personal experience, it is more intuitive for the cursor to be positioned at the end of the text.
I've attached a video demonstrating the old and new behaviour:
[screen-capture.webm](https://github.com/plankanban/planka/assets/16878981/34a39eb2-fc20-4d6b-8933-2b215f0027a1)
Cheers
Hannes
=> feat: :children_crossing: enhance edit usability

server/config/custom.js
Fixes #784 by defining it to be an empty array so it properly parses/sets to config.
=> Handle WEBHOOKS env variable being unset

server/api/helpers/utils/send-webhooks.js
This pull would re-introduce the local event types for programmatically generation of event types: https://github.com/plankanban/planka/issues/793
It would be even more useful if the module could export the constant so one could access it by invocation. I'm not sure how the sails framework works in that case / one would nicely implement it.
Cheers
Hannes
=> refactor: :recycle: webhook define all possible event types in module

server/api/helpers/utils/send-webhooks.js
This update adds a default `user-agent` to the header, which includes the base URL. This enhancement allows for differentiating multiple instances on the webhook and creating links to events without hardcoding any base URLs.
Prior to this change, the default user-agent of node-fetch was "node".
Cheers,
Hannes
=> feat: :sparkles: add custom user agent to webhook with base url

server/api/helpers/utils/send-webhooks.js
This adds very basic types to the webhook function, so one can create programatically types for a payload on the webhook: https://github.com/plankanban/planka/issues/793
=> docs: :label: add types to webhook function

server/api/controllers/access-tokens/exchange-using-oidc.js, server/api/controllers/show-config.js, server/api/helpers/users/get-or-create-one-using-oidc.js, server/api/hooks/oidc/index.js, server/config/custom.js
I am working for the French government, which employs a very strict OIDC provider. Government applications often adhere to more stringent implementations of the OIDC specification to enhance security.
To properly connect Planka with their OIDC provider, I needed to add greater flexibility to the current openid-client integration. The initial implementation was missing some important features, such as support for signed user info.
Given the nature of this work, it's crucial to clearly explain every change, I tried to be as explicit as possible in my commits.
Here's a summary:
- Allow using the default value of `response_mode` or specifying a custom value without introducing breaking changes.
- Ensure the client can handle signed user info responses from strict OIDC providers.
- Expand …
=> Enhance OIDC Support for Compatibility with Strict Providers

docker-compose-dev.yml
Currently docker dev postgres fails because the healthcheck uses an account and db which has not been initialised. This PR updates the username and the db so that correct credentials are used
=> Update user and db  for healthcheck docker-compose-dev.yml

charts/planka/templates/deployment.yaml
In case planka is installed with a PV associated to the planka pod, to persist attachments and avatars for example, the default update strategy for the deployment will fail. The default "rolling update" strategy would indeed try to start a new pod before stopping the old one. But as the PV is attached to the old pod,  the new pod will fail to attach and so will stay in "container creating" mode, and the old pod will never be stopped.
To avoid that, adding a condition on the deployment to use the "recreate" update strategy if the persistence is enabled. This will ensure the old pod is stopped and so the PV is detached  before trying to attach the new one.
=> feat: Change the update strategy in case of persistence

server/.env.sample, server/api/controllers/attachments/create.js, server/api/controllers/boards/create.js, server/api/controllers/projects/update-background-image.js, server/api/controllers/users/update-avatar.js, server/api/helpers/utils/receive-file.js, server/config/custom.js, server/config/routes.js, server/package-lock.json, server/package.json, server/utils/logger.js
I wanted to package planka for deployment as a regular system service on linux (not in a container). Packaging standards and the filesystem conventions on linux require static code, configuration, and writable data directories to be separated.
Specifically, the directories for user-uploaded files (project backgrounds, user avatars), card attachments, and the server logfile need to be outside the main directory.
There are already custom-config properties to set the location of the upload directories, but they are served with the default static-file route in Sails, which means they can only be in subdirectories of the `public/` directory (this contains the app code, so in a normal deploy this directory isn't going to be writable).
To fix that, I've added two custom routes that will serve …
=> Configurable file storage locations

client/src/components/CardModal/Tasks/Add.jsx
Modified the handleFieldKeyDown function in Add.jsx to handle Ctrl+Enter keypress events. This change allows creating multiple tasks from each non-empty line in the text field when Ctrl+Enter is pressed, while maintaining the existing functionality for creating a single task on Enter.
A similar feature is in Trello, which I find essential when copy-pasting a list of items and want them to be multiple tasks and not just a huge single task.
=> feat: Add multi-task creation with Ctrl+Enter in Add.jsx

server/api/controllers/access-tokens/exchange-using-oidc.js, server/api/controllers/show-config.js, server/api/helpers/users/get-or-create-one-using-oidc.js, server/api/hooks/oidc/index.js
Sometimes, Planka might boot before the OIDC server is ready to respond. In this case the bootup will freeze with an error:
```
planka-1         |2024-11-18 08:01:14 [E] Failed to lift app: Error: getaddrinfo ENOTFOUND auth.tohka.us
```
In this state the server is not "running", but it also does not exit, leading to a server hang.
Instead, create the client on first OIDC request (lazy loading). If the OIDC client communication fails, the server will still be running but OIDC related requests (login, configuration) will fail with a 500 Internal Server Error and a log explaining the OIDC error:
```
planka-1         |2024-11-18 09:06:39 [W] Error while initializing OIDC client: Error: getaddrinfo ENOTFOUND auth.tohka.us
planka-1         |2024-11-18 09:06:39 [E] Sending 500 ("Server Error") …
```
=> fix: Lazy initialize OIDC client

client/public/index.html
Opening a project page directly by its URL link causes a `404 Not Found` error for the `http://planka/boards/logo192.png` path.
If we open it from the main page, this basic part is already loaded and won't re-render after navigating, but accessing a specific project or card will render the whole HTML, therefore the relative logo192.png path will not be found there.
Simply added the `%PUBLIC_URL%` to the link component.
=> fix: apple-touch-icon not found

docker-backup.sh, docker-restore.sh
`docker-backup.sh` and `docker-restore.sh` didn't quote variables, which prevented them from running in certain environments. This PR adds consistent quotation for all variables in those scripts.
Ref.: https://www.shellcheck.net/wiki/SC2046 https://www.shellcheck.net/wiki/SC2086
=> fix: quote variables to prevent word splitting

Dockerfile, config/development/Dockerfile.client, config/development/Dockerfile.server
- Prevent mismatch of node and npm by removing `@latest` tag. `0.737 npm error engine Not compatible with your version of node/npm: npm@11.0.0`
- Fixes casing warnings on docker build ` => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)`
=> build: 🐛 don't use explicit latest npm version

server/config/datastores.js
By default sails-postgres was using `public` even though default `search_path` of db user was different. 
Source: https://stackoverflow.com/a/57210065
Did not face this same issue with Knex migrations
=> [FIX] configurable db schema name

docker-compose-dev.yml, docker-compose.yml, server/.env.sample, server/start.sh
Docker secrets are exposed as files in `/run/secrets/` inside the container instead of as environment variables. To support deployments where the passwords are stored in secrets, this patch adds support for loading the `SMTP_PASSWORD`, `SECRET_KEY` and the database password from files, using the `__FILE` suffix convention found in many docker images.
The database password is part of the `DATABASE_URL` environment variable, if a password is used at all. To support injecting the password into the DATABASE_URL without having to use the whole URL as the secret, the `start.sh` replaces the string `${DATABASE_PASSWORD}` in the `DATABASE_URL` environment variable by the contents of the `DATABASE_PASSWORD` variable, which can now also be loaded from the corresponding file passed in …
=> feat: Support loading passwords from docker secrets

Dockerfile.dev, docker-compose-dev.yml, server/nodemon.json
* Updated the base image in `Dockerfile.dev` from `node:18-alpine` to `node:lts-alpine` to use more or less the same as for production docker build (where the client is build lts and server is 18... so yeah not really...)
* Removed the `USER node` directive, to prevent permission issues as we hook the whole folder into the container.
* Modified the `docker-compose-dev.yml` file to enhance the database healthcheck. The new healthcheck ensures not only postgres is ready but also the database is ready by running a sample query (`SELECT 1`) and adjusts the interval, retries, and start period for better reliability.
* Added a `nodemon.json` configuration file to watch only relevant files (node_modules would be ignored but not files like the python venv) and avoid rapid successive restarts with …
=> build: :technologist: specify nodemon and remove USER directive for dev container

docker-compose-dev.yml, server/.env.sample
- Add BASE_URL to docker-compose-dev so the first run does not fail if someone's forgotten to copy .env
=> fix: Improve dev setup

client/src/locales/da-DK/core.js
Corrected a word from plural to singular, and now it fits the context.
=> Danish translation small fix

server/config/locales/en-GB.json, server/config/locales/en-US.json
This pull request addresses a typo in the two English translations when an email notification is sent
- Currently, the email reads: "Your Were Added to Card"
- The email should read: "You Were Added to Card"
This typo is present in both en-US and en-GB.
Thank you for considering this small change, and for all your excellent work on the project!
=> Fix: typo in en-GB and en-US locales

charts/planka/Chart.yaml, charts/planka/templates/ingress.yaml, charts/planka/values.yaml
- Updated postgres chart to use legacy repository(bitnamilegacy) even though it's required to pass "allowInsecureImages"
- Added labels for ingress. This is in order to allow service like homepage(https://github.com/gethomepage/homepage) to fetch ingress dynamically and add it to dashboard
=> Minor helm chart updates
