README.md
docker-compose-dev.yml

Hi!
Thanks for developing planka - it looks really great! I am looking for a simple personal ticketing system and will try to use planka :).

Add dev documentation and local db server

---

client/src/locales/de/embed.js

I changed the translation from english to german.

embed.js DE version of Planka v.1

---

client/src/store.js

[Redux Devtools](https://github.com/zalmoxisus/redux-devtools-extension) is a browser extension that provides utilities to work with Redux.
This pull request enables the Redux Devtools  extension in development mode.

Enable Redux Devtools in development mode

---

client/src/locales/cs/core.js

fix dateFns locale for Czech language

Fix datepicker language code for Czech language

---

.gitignore

just a simple ignore to stay up2date with the repo :)

Ignore custom docker compose changes

---

client/src/components/CardModal/CardModal.module.scss

Fix invalid white-spaces in card description

---

client/src/locales/de/core.js

Fix several spelling errors and grammar

Improve German Language

---

server/config/env/production.js

This PR aims to fix the proxy init code for Sails.js.

Fix: Proxy Forwarding fix

---

Dockerfile
client/config-overrides.js
client/package-lock.json
client/package.json
client/public/index.html
client/src/api/socket.js
client/src/constants/Config.js
client/src/constants/Paths.js
server/config/views.js

Hi,
Regarding the issue #272 (maybe #43 and #111 also) I propose this solution.
It can be too complex but there is no straight-forward way to implement a react application base url at runtime.
If you have any questions/remarks I would be very happy to improve this implementation.
Thanks for maintaining this great project!

fix: #272 Front end application base url with path

---

README.md

Please consider this PR since not everyone wanted to use docker, especially for those who have minimum VM specification and can't run a docker.

Add documentation for installing Planka without Docker

---

README.md

Oops sorry i forgot that you need to copy index.html to views/index.ejs as stated in https://github.com/plankanban/planka/blob/master/Dockerfile#L29 🙏

Forgot to copy index.html to index.ejs

---

client/src/components/List/CardAdd.jsx
client/src/containers/ListContainer.js
client/src/entry-actions/cards.js
client/src/locales/en/core.js
client/src/sagas/core/services/cards.js
client/src/sagas/core/watchers/cards.js

Also edited en translation to: 'Enter card title... [Ctrl+Enter] to open'
Press Ctrl+Enter to open a card and edit just after creation.

feat: Added feature - open card once created with Ctrl+Enter

---

README.md
backup.sh
restore.sh

Closes https://github.com/plankanban/planka/issues/128

Feat: Adds manual Backup and Restore scripts

---

docker-compose.yml
server/.env.sample
server/db/knexfile.js

Reverts eea57ff1211db87144f74923d79c8d8e671bae73

revert: Allow postgres connections that require ssl mode

---

client/src/components/CardModal/Tasks/Tasks.jsx
client/src/components/CardModal/Tasks/Tasks.module.scss

Added task counter in Card Modal
Fixes issue #467

fix #467: Add task counter in Modal

---

client/src/locales/zh/core.js

detectAutomatically should be translate to '自动检测'

fix chinese translation

---

client/src/models/List.js

This is an extension of #713 to search in description text too

Search in description

---

charts/planka/README.md

- Make it clear what instructions to follow for developing the chart, or just using it.
- Remove link to my old chart repo.
Mildly related to https://github.com/plankanban/planka/issues/739

Update Kubernetes README

---

docker-compose-dev.yml
docker-compose.yml
server/api/hooks/smtp/index.js
server/config/custom.js

This is the additional environment variable to enable EHLO authentication with SMTP.

SMTP_NAME variable

---

server/api/helpers/utils/send-webhooks.js

Fixed application crash when a webhook fetch fails, for example, when the webhook url is unavailable

fix: Fixed application crash when the webhook url is unavailable

---

server/config/http.js

Hi,
I disable x-powered-by header which is a security issue against automated attacks.
Best regards,

fix: disable x-powered-by

---

client/src/locales/fr-FR/login.js

Update french translation (invalid credentials)

fix: update french translation

---

charts/planka/Chart.yaml
charts/planka/templates/service.yaml
charts/planka/values.yaml

Support service annotations which can be helpful when running planka in a cloud provider.
resolves https://github.com/plankanban/planka/issues/902

feat(chart): Support Service Annotations

---

docker-compose-dev.yml
docker-compose.yml
server/.env.sample
server/api/helpers/actions/create-one.js
server/api/helpers/cards/delete-one.js
server/api/helpers/utils/send-telegram-message.js
server/config/custom.js

Contributions made by @Elllone of [DiklosGroup](https://github.com/DiklosGroup)
<hr/>
This PR adds notification integration that will alert a chat, group, or topic in telegram about various actions:
To use it, the user must obtain a _bot_token_ from the bot in telegram, as well as a _chat_id_. If the user needs to send notifications to a specific topic, they will also need the _message_thread_id_.
So, copy the bot_token to the `TELEGRAM_BOT_TOKEN` environment variable, the chat_id to the `TELEGRAM_CHAT_ID` environment variable, and, if needed, the message_thread_id to the `TELEGRAM_THREAD_ID` environment variable.

Add telegram bot notification integration

---

README.md

I create a postman doc of api server planka

Add planka postman api

---

client/src/components/Login/Login.jsx
client/src/sagas/login/services/router.js

Add enforce_oidc_login param to /login to redirect to OIDC directly

---

client/src/components/cards/Card/ProjectContent.jsx
client/src/models/Card.js
client/src/models/Comment.js
client/src/selectors/comments.js
server/api/hooks/query-methods/models/Comment.js
server/api/models/Card.js
server/db/migrations/20250523131647_add_comments_counter.js

closes: https://github.com/plankanban/planka/issues/1136

feat: :sparkles: show count of comments on card information
